---
- hosts: all
  become: yes

  vars_files:
    - vars.yaml

  pre_tasks:
    - name: install pip3
      apt: name=python3-pip
    - name: Install psycopg2 for ansible to be able to create postgresql users
      pip: name=psycopg2-binary
      become: yes

  roles:
    - anxs.postgresql
